import { Document, Page, StyleSheet, Text, View } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    padding: 32,
  },
  title: {
    fontSize: 20,
    marginBottom: 12,
  },
  body: {
    fontSize: 12,
    lineHeight: 1.4,
  },
  section: {
    marginBottom: 10,
  },
});

type A4PdfDocumentProps = {
  title: string;
  descriptor?: Record<string, unknown>;
};

export function A4PdfDocument({ title, descriptor }: A4PdfDocumentProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.section}>
          <Text style={styles.title}>{title}</Text>
          <Text style={styles.body}>
            Generated by the configurator sidebar. This is a placeholder A4 PDF.
          </Text>
        </View>

        {descriptor ? (
          <View style={styles.section}>
            <Text style={styles.body}>Descriptor:</Text>
            <Text style={styles.body}>
            </Text>
          </View>
        ) : null}
      </Page>
    </Document>
  );
}
