import { Document, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import { pdf } from "@react-pdf/renderer";
import { createElement } from "react";

const pdfStyles = StyleSheet.create({
  page: {
    padding: 32,
  },
  title: {
    fontSize: 20,
    marginBottom: 12,
  },
  body: {
    fontSize: 12,
    lineHeight: 1.4,
  },
  section: {
    marginBottom: 10,
  },
});

type PdfSection = {
  heading: string;
  lines: string[];
};

function getPdfSections(): PdfSection[] {
  return [
    {
      heading: "Info",
      lines: ["Generated by the configurator.", "Placeholder A4 PDF."],
    },
  ];
}

type A4PdfDocumentProps = {
  title: string;
};

export function A4PdfDocument({ title }: A4PdfDocumentProps) {
  const sections = getPdfSections();

  return (
    <Document>
      <Page size="A4" style={pdfStyles.page}>
        <View style={pdfStyles.section}>
          <Text style={pdfStyles.title}>{title}</Text>
        </View>

        {sections.map((section) => (
          <View key={section.heading} style={pdfStyles.section}>
            <Text style={pdfStyles.body}>{section.heading}</Text>
            {section.lines.map((line, idx) => (
              <Text key={`${section.heading}-${idx}`} style={pdfStyles.body}>
                {line}
              </Text>
            ))}
          </View>
        ))}
      </Page>
    </Document>
  );
}

export type GeneratePdfOptions = {
  title: string;
};

export async function generateAndOpenPdf(options: GeneratePdfOptions) {
  await new Promise<void>((resolve) => setTimeout(resolve, 0));

  const instance = pdf(
    createElement(A4PdfDocument, {
      title: options.title,
    })
  );

  const blob = await instance.toBlob();
  const url = URL.createObjectURL(blob);

  window.open(url, "_blank", "noopener,noreferrer");

  window.setTimeout(() => URL.revokeObjectURL(url), 60_000);
}

let isGeneratingPdf = false;

async function handleMakePdf() {
  if (isGeneratingPdf) return;
  isGeneratingPdf = true;
  try {
    await generateAndOpenPdf({
      title: "Configurator Export (A4)",
    });
  } finally {
    isGeneratingPdf = false;
  }
}

export const e3dsPdfCommandHandlers = {
  makepdf: handleMakePdf,
};
