export type PdfSection = {
  heading: string;
  lines: string[];
};

/**
 * Base texts for the PDF.
 * Keep content here so `PdfDocument.tsx` focuses on layout + generation.
 */
export function getBasePdfSections(): PdfSection[] {
  return [
    {
      heading: "Info",
      lines: ["Generated by the configurator.", "Placeholder A4 PDF."],
    },
  ];
}
